# x - x position in meters
# y - y poistion in meters
# yaw - yaw angle orientation in degrees
# frame - goal frame (map or odom)
goals_frame: map
goals:
 - {x: 3.4, y: 0.3, yaw: 90.0}
 - {x: 3.4, y: 2.0, yaw: 90.0}
 - {x: 0.0, y: 0.5, yaw: 0.0}
