# x - x position in meters
# y - y poistion in meters
# yaw - yaw angle orientation in degrees
# frame - goal frame (map or odom)
goals_frame: map
goals:
 - {x: -1.0, y: 3.0, yaw: 90.0}
 - {x: -3.0, y: 3.0, yaw: -180.0}
 - {x: -3.0, y: 1.0, yaw: -90.0}
 - {x: -1.0, y: 1.0, yaw: 0.0}
